CREATE TABLE PRODUCT (
    ID INTEGER  NOT NULL,
    CART_ID INTEGER NOT NULL,
	AMOUNT INTEGER  NOT NULL,
    DESCRIPTION VARCHAR2(255)
);

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_CART_FK FOREIGN KEY(CART_ID) REFERENCES CART(ID);