CREATE TABLE CART(
    ID INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE CART ADD  PRIMARY KEY (ID);
CREATE SEQUENCE CART_ID START WITH 1;
ALTER SEQUENCE CART_ID NOCACHE;

